### PR TITLE
Enable automatic per app language

### LINKED ISSUE #330: Use generateLocaleConfig gradle feature
With latest versions of gradle 8.0, gradle can automatically generate [locale config file](https://github.com/ev-map/EVMap/blob/master/app/src/main/res/xml/locales_config.xml)

More information here:
- https://developer.android.com/guide/topics/resources/app-languages#auto-localeconfig

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
Fixes #330

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
getApplicationsLocales return default on devices before Android 12?

**Comment by johan12345** [comment]
> getApplicationsLocales return default on devices before Android 12?

no, it [returns an empty list](https://github.com/androidx/androidx/blob/df78e0577adbd9964c6ed0ab4be6d51a1c5692c0/appcompat/appcompat/src/main/java/androidx/appcompat/app/AppCompatDelegate.java#L835) before Android 12 if no app-specific locale has been chosen.

**Comment by Jean-BaptisteC** [comment]
Is it ok to return default value, if version of Android is under Android 12?

**Comment by johan12345** [comment]
Yes, the `getAppLocale()` function is used by the settings screen to decide what to show as the currently chosen locale, so it needs to be one of the language codes from [this array](https://github.com/ev-map/EVMap/blob/master/app/src/main/res/values/arrays.xml#L14-L24).

**Comment by Jean-BaptisteC** [comment]
I have updated getAppLocale function, but I think it can't be work on device under API 34.
To get supportedLocale, I have seen a solution to parse the xml localeconfig file, but I'm not sure it's the best solution.

**Comment by johan12345** [comment]
Yeah, what we would basically need is a backwards-compatible version of [`LocaleConfig.getSupportedLocales()`](https://developer.android.com/reference/android/app/LocaleConfig#getSupportedLocales()).

But: We still have a list of supported locales that is manually maintained in `pref_language_values` in `arrays.xml`. So for now, we can use that one to match the selected locale against the supported ones. I implemented that now.

It seems that someone already suggested to add that `getSupportedLocales` compatibility method: https://issuetracker.google.com/issues/288303238 - if that gets implemented at some point, we can of course switch to that and also use it to automatically populate the `pref_language_values` array.

**Pull request merged**
