### PR TITLE
Adding Romanian language support

### PR DESCRIPTION
**Pull request by iboboc**
Adding support in app for Romanian Language.

### CODE REVIEW

**Comment by johan12345** [comment]
Hi @iboboc, thanks a lot for the contribution!

If you look at the Android Lint [report](https://github.com/ev-map/EVMap/actions/runs/4721068810/jobs/8428401943?pr=274) there are a couple errors, probably all for the `<plurals>` strings - plurals seem to have a special case for the number 2 in Romanian which needs to be specified using `<item quantity="few">` for Android. Could you take a look at this?
Also, the language still needs to be added to the `supportedLocales` list in `build.gradle` (just like I recently did for Portuguese [here](https://github.com/ev-map/EVMap/commit/d77f13682d04725f31a1bdba7ae9f669d6eccc4d#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9L12)).

**Comment by iboboc** [comment]
Thanks for feedback Johan, it was not clear for me why the build failed (tested myself and looks good).
Seen the warning for "few" but ignore it.

I'll fix it and add a new patch (but please be kind with me, I am not that experienced).

Keep up the good work!

**Comment by johan12345** [comment]
Looks good now, thanks! 👍

**Comment by iboboc** [comment]
Thanks. Just a question, when is going to be published in Play Store?

**Comment by johan12345** [comment]
I uploaded the release to the Play Store now, review by Google might take a couple days.

**Pull request merged**
