### PR TITLE
Migrate to build kotlin script

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
This PR migrated to KTS.
- I know KTS has issues about performance, this PR can be merged when problem is fixed, let's see the difference with Groovy and KTS about build time.

Todo:
- [x] Fix ext variables, two options, use extra (declaration is present build.gradle.kts and app/build.gradle.kts) or create a new class in project to store variables -> https://stackoverflow.com/questions/45753733/ext-in-buildscript-can-not-be-recognised-by-gradle-kotlin-dsl
- [x] Fix KotlinOptions in tasks (Is it used to specify which jvm is used during specific build tasks ?)
- [x] Fix not recognized implementations (googleImplementation, ...)
- [x] Fix functions, Android Studio has converts function, but it doesn't work (I'm not an expert in Kotlin, help would be appreciated)
- [x] Fix errors about API_KEY
- [x] Fix error about version code auto increment

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
@johan12345 I have almost done migration, I have just need help for 2 latest things ->  to fix the error about version code auto-increment and for rework decode function/xorWithKey function

**Comment by johan12345** [comment]
Hi, I have managed to fix those two things, could you enable "Allow edits from maintainers" on your PR so I can push these changes?
When I'm back home next week I can test how the build times compare between the Kotlin and Groovy versions.

Unfortunately, if we plan to keep this PR around for a longer time until the performance is improved, git probably won't be able to automatically merge any future changes in the Groovy buildscript (app version and dependency updates) into the Kotlin one. So that needs to be done manually once we decide to merge it.

**Comment by johan12345** [comment]
#### Build speed benchmark:
- checkout branch `kts` or revision before changes (23a3adc)
- restart Android Studio
- sync project with Gradle files, wait for it to complete
- `gradle clean assembleGoogleNormalDebug`

**Groovy:**
first build: 1m17s
second build: 40s
third build: 33s

**Kotlin:**
first build: 1m23s
second build: 42s
third build: 34s

I've tested a couple of times, and these times seem relatively reproducible.
So: Kotlin is slower, but the difference is pretty much negligible in our case (just a couple of seconds).

**Comment by Jean-BaptisteC** [comment]
Thanks for your help to finishing PR :)

I think you can retry benchmark, with a more recent of gradle because 8.3 and 8.4 versions of gradle reduce the build time for Java compilation
More information here -> https://docs.gradle.org/8.4/release-notes.html

**Comment by johan12345** [comment]
Yep, Gradle 8.4 speeds it up a bit more and makes Kotlin and Groovy about the same. Thanks!

**Groovy**:
first build: 1m15s
second build: 39s
third build: 32s

**Kotlin**:
first build: 1m15s
second build: 39s
third build: 31s

Now we just need to rebase it on top of the current `master`, making sure to include all the latest version and dependency updates. @Jean-BaptisteC, would you like to do that?

**Comment by orubel** [comment]
OK so hate to point this out after all the hard work BUT... This is not a FIX. This only makes Groovy slower to MATCH Kotlin numbers. Look at the original tests (https://github.com/gradle/gradle/issues/15886)

Groovy first test was 30s. Now it is 1m 15 secs. You made it SLOWER! You did not improve anything. This deliberately makes Groovy slower to match Kotlin!! 

This is GIMPING a language... not a fix

**Comment by johan12345** [comment]
Did you even look at the numbers I measured? For this project it obviously does not make a significant difference.

**Comment by orubel** [comment]
@johan12345 I did. I compared them to original tests (see above). You tests REVERTED Groovy speeds.

**Comment by johan12345** [comment]
The measurements in this PR are on the EVMap app. The "original" measurements in the Gradle issue are on a completely unrelated project, and of course not comparable.

**Comment by orubel** [comment]
@johan12345 but the buildtimes should be comparable. It should not be off by THAT MUCH. If this is the fix, Kotlin should be having that 30s time as well.

Are there not consistent test environments??

**Comment by orubel** [comment]
@johan can you show the abi, non-abi and config full data and supply the test so we can run our own benchs/test?

**Comment by johan12345** [comment]
Why should build times of completely different projects on completely different systems be comparable? What matters to me at the moment is the performance for compiling this specific Android app, not some other project that the Gradle team uses for benchmarking, which seems to be less complex and therefore only needs 30s to compile. At no point was there a "deliberate 3x increase" in Groovy build time, EVMap never compiled that fast. 

On thie project, compile times were about the same between Groovy and Kotlin on both Gradle 8.0 ([first test](https://github.com/ev-map/EVMap/pull/298#issuecomment-1765030149)) and 8.4 ([second test](https://github.com/ev-map/EVMap/pull/298#issuecomment-1765091903)). All the info you need to reproduce these tests on your system are in the comments I posted, and the code to compile is in this repo. 

I suppose execution of the build script itself is only a very minor part of the compile time compared to e.g. the Kotlin compiler itself, annotation and resources processing, etc. - which are all independent of which language is used for the build scripts.

**Comment by orubel** [comment]
@johan12345 no one said there was a 'deliberate 3x increase' to Groovy. But you are saying there was no consistent test from the first issue to the HERE and am not seeing backend changes nor the test project being used for this measurement.

If someone can, please supply the Gradle backend changes and a consistent test project so others can test this PR? I am assuming this is a private Android project that is being tested.

**Comment by johan12345** [comment]
As I said, the code to compile is in this repo. It is not private. 

Of course there was no consistent test between the "original issue" and here because the original issue (in the Gradle repository) is about *general performance* of Gradle build scripts in Kotlin and Groovy *across different projects*, while this PR (in the EVMap repository) is about migrating *this project* to Kotlin build scripts and testing whether performance is adequate *for this project*.

**Comment by orubel** [comment]
@johan12345 ok. And to understand, the PR changes are literally just the build.gradle files??

**Comment by johan12345** [comment]
Yeah

**Comment by orubel** [comment]
@johan12345 is restart Android Studio and sync project with Gradle files necessary to get those statistics?

**Comment by johan12345** [comment]
If you run it just from the command line, the equivalent thing would probably be restarting the Gradle daemon (though I have not tested that). As you see I do get different build times for the first, second and third build after a restart, probably due to caching (subsequent tests without restarting are the same as the third build).

**Comment by orubel** [comment]
@johan12345 well what are you trying to do? refresh dependencies? Clear cache?

**Comment by johan12345** [comment]
What I'm trying to do is make the build times reproducible, and that seems to do the trick 🙄

**Comment by orubel** [comment]
@Johan12345 I understand but I mean by 'restarting gradle' as you stated. From a testing perspective, restarting gradle is not a testing solution. Thats why I ask what are you trying to do? Refresh dependencies? clear cache? what?

**Comment by johan12345** [comment]
I'm sorry, but I don't know why I need to defend myself here in front of someone who kept yelling at me in all-caps even before looking into what project this PR is in and which changes were implemented in it. 

If you want to contribute to this project and have a better testing methodology to propose, feel free to try it out and document your method and results. If you can show that Kotlin is significantly slower in a common situation I may consider reverting to Groovy.

**Pull request merged**
